    #Seleciona a imagem Ubuntu
FROM ubuntu

    #Atualiza o Ubuntu
RUN apt-get update

    #Instala apps necessários
RUN apt install apache2 -y
RUN apt install curl -y
RUN apt install zip -y
RUN apt install software-properties-common ca-certificates lsb-release apt-transport-https
RUN LC_ALL=C.UTF-8 sudo add-apt-repository ppa:ondrej/php
RUN apt update -y
RUN apt install php7.4 -y
RUN apt install -y php7.4-cli php7.4-json php7.4-common php7.4-mysql php7.4-zip php7.4-gd php7.4-mbstring php7.4-curl php7.4-xml php7.4-bcmath

    #Conf do servidor
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install
RUN mkdir /var/www/html/teste
COPY index.html /var/www/html/teste/

    #Serviços
RUN /etc/init.d/apache2 start
